### ISSUE TITLE
Remove all references to deprecated Firebase Simple Login

### ISSUE THREAD

**Issue by jwngr** [firebase/angularfire-seed#74]
We want people to upgrade to the latest version of Firebase with the latest and greatest authentication methods and it having Simple Login sprinkled throughout the README and the code is causing confusion for some users.

**Comment by kjhughes** [comment]
Seeking clarification on the code update part of the issue: While [this commit](https://github.com/firebase/angularfire-seed/commit/55fde659a27069df05e5fd9afd1f7077328ccfb7) migrated angularfire-seed to the new authentication methods, it did so by modifying app/js/simpleLogin.js without changing its name.  The issue here is to eliminate use of the name 'simpleLogin' because it connotes association with the deprecated [Firebase Simple Login](https://www.firebase.com/docs/web/api/firebasesimplelogin/) library?

**Comment by jwngr** [comment]
Yes, you are exactly right. This is using the newest auth methods, but the naming is the confusing thing for people, myself included. Ideally we would not use the phrase "Simple Login" at all in this repo, including in filenames, variable names, and comments.

**Comment by djindjic** [comment]
oh yes, I agree with that. I'm not very deep in angularfire but I currently have a problem with login and wanted to ask is it old simple login or just name convection. So this is new auth methond and just file named simpleLogin.js?

**Comment by jwngr** [comment]
Yes, it is the new methods with the old name. We will fix this.

**Comment by katowulf** [comment]
Remove anything prefixed with "simple" in 1.0.0 to avoid confusion.
