### ISSUE TITLE
Please configure app/js/config.js before running! always show

### ISSUE THREAD

**Issue by newaeonweb** [firebase/angularfire-seed#75]
Even configuring the Instance reference to Firebase, the warning still showing

**Comment by GhislainG** [comment]
I have the same issue, but when I remove : 
 // double check that the app has been configured before running it and blowing up space and time
  .run(['FBURL', '$timeout', function(FBURL, $timeout) {
    if( FBURL.match('//INSTANCE.firebaseio.com') ) {
      angular.element(document.body).html('<h1>Please configure app/js/config.js before running!</h1>');
      $timeout(function() {
        angular.element(document.body).removeClass('hide');
      }, 250);
    }
  }]);

from config.js, it works perfectly.

**Comment by katowulf** [comment]
It would be hard to come to the conclusion that this is the same issue simply because you receive the same error message. 

If you are receiving that error, and removing the check fixes the error, then your FBURL is incorrectly set to INSTANCE.friebaseio.com. This would indicate that things will not work perfectly (which is why the check exists).

If the check is incorrect, then actual data indicating which URL it can't parse, and troubleshooting that helps explain the bug would be appropriate here.
